name: com.example.simple_animal_app
description: A simple Flutter app that displays a text of an animal (Cat or Dog) and changes the text and icon when clicked.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true